export const SAVE = 'SAVE';
export const FIND_ALL_WIDGETS = 'FIND_ALL_WIDGETS';
export const FIND_WIDGETS_FOR_LESSON_TOPIC = 'FIND_WIDGETS_FOR_LESSON_TOPIC';
export const DELETE_WIDGET = 'DELETE_WIDGET';
export const ADD_WIDGET = 'ADD_WIDGET';
export const SELECT_WIDGET_TYPE = 'SELECT_WIDGET_TYPE';
export const WIDGET_NAME_UPDATED = 'WIDGET_NAME_UPDATED';

export const HEADING_TEXT_UPDATED = 'HEADING_TEXT_UPDATED';
export const HEADING_SIZE_UPDATED = 'HEADING_SIZE_UPDATED';

export const PARAGRAPH_TEXT_UPDATED = 'PARAGRAPH_TEXT_UPDATED';

export const LIST_ITEMS_UPDATED = 'LIST_ITEMS_UPDATED';
export const LIST_TYPE_UPDATED = 'LIST_TYPE_UPDATED';

export const SRC_UPDATED = 'SRC_UPDATED';

export const LINK_TEXT_UPDATED = 'LINK_TEXT_UPDATED';
export const HREF_UPDATED = 'HREF_UPDATED';