export const SAVE = 'SAVE';
export const FIND_ALL_WIDGETS = 'FIND_ALL_WIDGETS';
export const FIND_WIDGETS_FOR_LESSON_TOPIC = 'FIND_WIDGETS_FOR_LESSON_TOPIC';
export const DELETE_WIDGET = 'DELETE_WIDGET';
export const ADD_WIDGET = 'ADD_WIDGET';
export const SELECT_WIDGET_TYPE = 'SELECT_WIDGET_TYPE';
export const WIDGET_NAME_UPDATED = 'WIDGET_NAME_UPDATED';

export const HEADING_TEXT_UPDATED = 'HEADING_TEXT_UPDATED';
export const HEADING_SIZE_UPDATED = 'HEADING_SIZE_UPDATED';